[package]
name = "shadowenv"
version = "1.3.2"
authors = ["Burke Libbey <burke@libbey.me>", "Lisa Ugray <lisa.ugray@shopify.com>", "Aaron Olson <aaron.olson@shopify.com>"]
edition = "2018"

[dependencies]
atty = "0.2"
blake2 = "0.8.0"
clap = "2.32.0"
dirs = "1.0.4"
exec = "0.3.1"
failure = "0.1.5"
hex = "0.3.2"
ketos = "0.11"
ketos_derive = "0.11"
libc = "0.2.48"
regex = "1.1.0"
serde = "1.0.85"
serde_derive = "1.0.85"
serde_json = "1.0.40"
shell-escape = "0.1.4"
shellexpand = "1.0.0"
signatory = "0.11.0"
signatory-dalek = "0.11.0"

[dev-dependencies]
quickcheck = "0.8.5"
quickcheck_macros = "0.8.0"
